name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Install vsce
        run: yarn add global vsce
      
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and Package VSCode Extension
        run: yarn vscode:prepublish

      - name: Publish to Marketplace
        run: yarn vscode:publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
